project_id = "qjngldfisjszeepmhxpa"

[functions.load-epstein-data]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.compute-graph]
verify_jwt = false

[functions.scrape-emails]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.seed-admins]
verify_jwt = false
